name: build-project-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v2
          
      - name: Delete old image
        run: |
          docker rmi djangokubernetesproject
          
      - name: Build new image
        run: |
          docker build -t djangokubernetesproject .
          
    
      - name: Makemigrations & Migrate
        run: |
          python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstaic
          
      - name: Migrate
        run: |
          docker-compose run web python3 manage.py migrate
          
      - name: Collectstatic
        run: |
          docker-compose run web python3 manage.py collectstatic 
          
          

