name: build-project-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
jobs:
  build:
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v2
          
      - name: Delete old image
        run: |
          docker rmi deepmatr1x/django:latest
          
      - name: Build new image
        run: |
          docker build -t deepmatr1x/django .
          
      - name: Migrate
        run: |
          docker run -i  djangokubernetesproject  python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic
          
      - name: Docker login
        run: |
          docker login

      - name: Docker image push
        run: |
          docker push deepmatr1x/django


       
          

