name: build-project-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
jobs:
  build:
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v2
          
      - name: login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with: 
          images: deepmatr1x/django

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}
 
      - name: Kubectl apply
        uses: okteto/apply@2.12.0
        with: 
          namespace: ${{secrets.NAMESPACE}}
          manifest: django-deployment.yml
 

      - name: Kubectl apply
        run: |
          kubectl apply -f django-deployment.yaml 

      - name: Expose external Service
        run: |
          kubectl expose deploy backend --type=LoadBalancer --port=8000 --name=django-svc
          
          
      - name: Get IP
        run: |
          kubectl get svc


       
          

