name: build-project-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v2
          
      - name: Delete old image
        run: |
          docker rmi djangokubernetesproject
          
      - name: Build new image
        run: |
          docker build -t djangokubernetesproject .
          
      - name: Migrate
        run: |
          docker run -i -t djangokubernetesproject sh

      - name: Makemigrations & Migrate
        run: |
          python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic
          
      - name: Docker login
        run: |
          docker login

      - name: Tag image
        run: |
          docker tag aba46f91e246 deepmatr1x/django:k8s_first

      - name: Docker image push
        run: |
          docker push deepmatr1x/django:k8s_first

       
          

